# Generated by Django 2.2.7 on 2019-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_tutor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
